language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t smm19sy/docker-react -f Dockerfile.dev .

.script:
  - docker run -e CI=true smm19sy/docker-react npm run test